---
- group:
    name: target
    state: present

- group:
    name: sudo
    state: present

- group:
    name: docker
    state: present

- user:
    name: trainee
    groups: target,sudo,docker
    shell: /bin/sh
    append: true
    home: /home/trainee

- apt:
    name: unzip
    state: latest

- unarchive:
    dest: /home/trainee
    src: files/Labsetup.zip
    owner: trainee
    mode: '770'

# common
- lineinfile:
    path: /etc/hsots
    line: 10.9.0.5 www.seed-server.com

# csrf
- lineinfile:
    path: /etc/hsots
    line: 10.9.0.5 www.example32.com

- lineinfile:
    path: /etc/hsots
    line: 10.9.0.105 www.attacker32.com

# xss
- lineinfile:
    path: /etc/hsots
    line: 10.9.0.5 www.example70.com

- lineinfile:
    path: /etc/hsots
    line: 10.9.0.5 www.example60.com

- lineinfile:
    path: /etc/hsots
    line: 10.9.0.5 www.example32c.com

- lineinfile:
    path: /etc/hsots
    line: 10.9.0.5 www.example32b.com

- lineinfile:
    path: /etc/hsots
    line: 10.9.0.5 www.example32a.com

- command: docker-compose up
  args:
    chdir: /home/trainee/Labsetup/
