---
- group:
    name: target
    state: present

- group:
    name: sudo
    state: present

- group:
    name: docker
    state: present

- user:
    name: trainee
    groups: target,sudo,docker
    shell: /bin/sh
    append: true
    home: /home/trainee

- apt:
    name: unzip
    state: latest

- unarchive:
    dest: /home/trainee
    src: files/Labsetup.zip
    owner: trainee
    mode: '770'

- command:
    shell: docker-compose up
    chdir: /home/trainee/Labsetup
